# Generated by Django 4.0.4 on 2022-05-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
